# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches:
      - main
  workflow_dispatch:

name: Quarto Render
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/install-quarto@v1
        with:
          # To install LaTeX to build PDF book
          tinytex: true
          # uncomment below and fill to pin a version
          # version: 0.9.105

      - uses: r-lib/actions/setup-renv@v1

      # Install any computing dependency you may need, usually either python and Jupyter or R
      # More specific examples will be shared on quarto-dev/quarto-actions project
      - name: preload
        run: |
          R -e 'source("cache.R")' || true
      - name: Render book to all format
        # Add any command line argument needed
        run: |
          quarto render

